export const colors = {
  light: {
    background: '#fff5f5',
    surface: '#fff0f0',
    headerBg: '#ffecec',
    headerText: '#4a2040',
    text: '#3a1a35',
    textSecondary: '#b08a9a',
    border: '#f0d0d8',
    inputBg: '#fce4e8',
    bubbleMe: '#f472b6',
    bubbleMeText: '#ffffff',
    bubbleOther: '#ffe4ec',
    bubbleOtherText: '#3a1a35',
    badge: '#f472b6',
    badgeText: '#ffffff',
    online: '#34d399',
    separator: '#f5d5dc',
    searchBg: '#fce4e8',
  },
  dark: {
    background: '#000000',
    surface: '#1c1c1e',
    headerBg: '#1c1c1e',
    headerText: '#ffffff',
    text: '#ffffff',
    textSecondary: '#8e8e93',
    border: '#38383a',
    inputBg: '#2c2c2e',
    bubbleMe: '#0a84ff',
    bubbleMeText: '#ffffff',
    bubbleOther: '#2c2c2e',
    bubbleOtherText: '#ffffff',
    badge: '#0a84ff',
    badgeText: '#ffffff',
    online: '#30d158',
    separator: '#38383a',
    searchBg: '#1c1c1e',
  },
};

export type ThemeColors = (typeof colors)['light'];
