export const colors = {
  light: {
    background: '#ffffff',
    surface: '#ffffff',
    headerBg: '#ffffff',
    headerText: '#000000',
    text: '#000000',
    textSecondary: '#8e8e93',
    border: '#c6c6c8',
    inputBg: '#f2f2f7',
    bubbleMe: '#007aff',
    bubbleMeText: '#ffffff',
    bubbleOther: '#e9e9eb',
    bubbleOtherText: '#000000',
    badge: '#007aff',
    badgeText: '#ffffff',
    online: '#34c759',
    separator: '#e5e5ea',
    searchBg: '#e5e5ea',
  },
  dark: {
    background: '#000000',
    surface: '#1c1c1e',
    headerBg: '#1c1c1e',
    headerText: '#ffffff',
    text: '#ffffff',
    textSecondary: '#8e8e93',
    border: '#38383a',
    inputBg: '#2c2c2e',
    bubbleMe: '#0a84ff',
    bubbleMeText: '#ffffff',
    bubbleOther: '#2c2c2e',
    bubbleOtherText: '#ffffff',
    badge: '#0a84ff',
    badgeText: '#ffffff',
    online: '#30d158',
    separator: '#38383a',
    searchBg: '#1c1c1e',
  },
};

export type ThemeColors = (typeof colors)['light'];
